apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netology-app
  template:
    metadata:
      labels:
        app: netology-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
      - name: multitool-container
        image: wbitt/network-multitool
        command: ["sleep", "infinity"]
