apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup nginx-service.default.svc.cluster.local; do echo waiting for service; sleep 2; done;']
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80