apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netology-app
  template:
    metadata:
      labels:
        app: netology-app
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: multitool-container
        image: wbitt/network-multitool:alpine-extra
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_PORT
          value: "8080"
