apiVersion: v1
kind: Service
metadata:
  name: netology-service
  namespace: default
spec:
  selector:
    app: netology-app
  ports:
  - name: web
    port: 9001
    targetPort: 80
  - name: multitool
    port: 9002
    targetPort: 8080
  type: ClusterIP
