apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: busybox-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-multitool
  template:
    metadata:
      labels:
        app: busybox-multitool
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo $(date) >> /output/shared.txt; sleep 5; done"]
        volumeMounts:
        - name: vol
          mountPath: /output
      - name: multitool
        image: wbitt/network-multitool:alpine-extra
        command: ["/bin/sh", "-c", "while true; do cat /input/shared.txt; sleep 5; done"]
        volumeMounts:
        - name: vol
          mountPath: /input
      volumes:
      - name: vol
        emptyDir: {}
